server:
  port: 8088

spring:
  application:
    name: jdbc-cache-app
  devtools.restart.enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_jdbc_cache
    username: root
    password: shiyuan
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      min-idle: 10
      max-active: 50
      max-wait: 10000
      test-on-borrow: true
      validation-query: SELECT 'x';
      test-while-idle: true
  jpa.show-sql: true
logging:
  level: warn
  file: ./logs/loc.log


#mybatis.config-location: classpath:mybatis-config.xml








